import {
  Avatar,
  Box,
  Button,
  Container,
  Flex,
  Heading,
  HStack,
  IconButton,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Posts: NextPage = () => {
  return (
    <Box py="100px">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.md">
        <Text color="gray.600">Publicado 30 Enero 2022. 04:00PM</Text>
        <Heading as="h1" size="xl" mb={4}>
          Choque entre un bus y un taxi dejó un fallecido en la vía Baños – Puyo
        </Heading>
        <Flex alignItems="center" justifyContent="space-between" mb={4}>
          <Flex alignItems="center">
            <Avatar
              size="sm"
              name="Jean Mayorga"
              src="https://bit.ly/sage-adebayo"
              mr="1"
            />
            <Link href="/posts/jean-paul-mayorga">
              <a>
                <Text color="gray.700" lineHeight="1" mb="0.5">
                  Jean Paul Mayorga
                </Text>
                <Text color="gray.600" fontSize="xs" lineHeight="1">
                  Mi Ciudad Stereo
                </Text>
              </a>
            </Link>
          </Flex>
          <Box>
            <Button rounded="full" aria-label="mas" variant="outline">
              Editar
            </Button>
          </Box>
        </Flex>
      </Container>
      <Container maxW="container.xl" padding={{ base: "0", lg: "auto" }} mb="8">
        <Box
          position="relative"
          height={{ base: "200px", lg: "500px" }}
          bg="black"
          overflow="hidden"
          borderRadius={{ base: "none", lg: "lg" }}
        >
          <Image
            src="/manoDios.jpg"
            alt="cover"
            layout="fill"
            objectFit="cover"
          />
        </Box>
      </Container>
      <Container maxW="container.md" position="relative">
        <HStack spacing={2} mb="8">
          <a
            href="https://twitter.com/share?text=How GitHub does take home technical interviews&amp;url=https://github.blog/2022-03-31-how-github-does-take-home-technical-interviews/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <IconButton
              aria-label="twitter"
              size="lg"
              variant="outline"
              borderRadius="full"
              colorScheme="twitter"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 273.5 222.3"
                height="18"
              >
                <path
                  d="M273.5 26.3a109.77 109.77 0 0 1-32.2 8.8 56.07 56.07 0 0 0 24.7-31 113.39 113.39 0 0 1-35.7 13.6 56.1 56.1 0 0 0-97 38.4 54 54 0 0 0 1.5 12.8A159.68 159.68 0 0 1 19.1 10.3a56.12 56.12 0 0 0 17.4 74.9 56.06 56.06 0 0 1-25.4-7v.7a56.11 56.11 0 0 0 45 55 55.65 55.65 0 0 1-14.8 2 62.39 62.39 0 0 1-10.6-1 56.24 56.24 0 0 0 52.4 39 112.87 112.87 0 0 1-69.7 24 119 119 0 0 1-13.4-.8 158.83 158.83 0 0 0 86 25.2c103.2 0 159.6-85.5 159.6-159.6 0-2.4-.1-4.9-.2-7.3a114.25 114.25 0 0 0 28.1-29.1"
                  fill="currentColor"
                ></path>
              </svg>
            </IconButton>
          </a>
          <a
            href="https://www.facebook.com/sharer/sharer.php?u=https://github.blog/2022-03-31-how-github-does-take-home-technical-interviews/&amp;t=How%20GitHub%20does%20take%20home%20technical%20interviews"
            target="_blank"
            rel="noopener noreferrer"
          >
            <IconButton
              aria-label="facebook"
              size="lg"
              variant="outline"
              borderRadius="full"
              colorScheme="facebook"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 15.3 15.4"
                height="18"
              >
                <path
                  d="M14.5 0H.8a.88.88 0 0 0-.8.9v13.6a.88.88 0 0 0 .8.9h7.3v-6h-2V7.1h2V5.4a2.87 2.87 0 0 1 2.5-3.1h.5a10.87 10.87 0 0 1 1.8.1v2.1h-1.3c-1 0-1.1.5-1.1 1.1v1.5h2.3l-.3 2.3h-2v5.9h3.9a.88.88 0 0 0 .9-.8V.8a.86.86 0 0 0-.8-.8z"
                  fill="currentColor"
                ></path>
              </svg>
            </IconButton>
          </a>
          <IconButton
            aria-label="copy"
            size="lg"
            variant="outline"
            borderRadius="full"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
              height="18"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"
              />
            </svg>
          </IconButton>
        </HStack>
        <Text as="p" textAlign="justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
          neque accusantium repudiandae magnam natus est iure voluptate
          distinctio, nemo nulla doloribus adipisci officiis laboriosam nostrum
          ad reiciendis architecto blanditiis illo.
        </Text>
        <br />
        <Text as="p" textAlign="justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
          neque accusantium repudiandae magnam natus est iure voluptate
          distinctio, nemo nulla doloribus adipisci officiis laboriosam nostrum
          ad reiciendis architecto blanditiis illo.
        </Text>
        <Text as="p" textAlign="justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
          neque accusantium repudiandae magnam natus est iure voluptate
          distinctio, nemo nulla doloribus adipisci officiis laboriosam nostrum
          ad reiciendis architecto blanditiis illo.
        </Text>
        <Text as="p" textAlign="justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
          neque accusantium repudiandae magnam natus est iure voluptate
          distinctio, nemo nulla doloribus adipisci officiis laboriosam nostrum
          ad reiciendis architecto blanditiis illo.
        </Text>
        <br />
        <Text as="p" textAlign="justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
          neque accusantium repudiandae magnam natus est iure voluptate
          distinctio, nemo nulla doloribus adipisci officiis laboriosam nostrum
          ad reiciendis architecto blanditiis illo.
        </Text>
        <br />
        <Text as="p" textAlign="justify">
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque,
          neque accusantium repudiandae magnam natus est iure voluptate
          distinctio, nemo nulla doloribus adipisci officiis laboriosam nostrum
          ad reiciendis architecto blanditiis illo.
        </Text>
      </Container>
    </Box>
  );
};

export default Posts;
