import { Box, Container } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Jumbo } from "../components";

const Home: NextPage = () => {
  return (
    <Box py="100px">
      <Container maxW="container.xl" padding={{ base: "0", lg: "auto" }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Jumbo
          image="/manoDios.jpg"
          title="Las manos de la Dios"
          description="La Mano de la Pachamama está ubicada dentro del complejo El Vuelo del Cóndor en el sector de Runtún a 7 km del centro de la ciudad de Baños."
        />
      </Container>
    </Box>
  );
};

export default Home;
