import { useState } from "react";
import { Box, Container, Heading, SimpleGrid, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { JumboForm } from "../components";

const Home: NextPage = () => {
  return (
    <Container maxW="container.xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        position="relative"
        height={500}
        bg="white"
        overflow="hidden"
        borderRadius="lg"
      >
        <Box position="absolute" zIndex={10} w="full" h="full">
          <Image
            src="/manoDios.jpg"
            alt="cover"
            layout="fill"
            objectFit="cover"
            className="zoomInOut"
          />
        </Box>
        <Box
          position="absolute"
          zIndex={10}
          bg="rgba(0,0,0,.5)"
          w="full"
          h="full"
        />
        <Box
          position="absolute"
          zIndex={20}
          top="50%"
          transform="translateY(-50%)"
          w="full"
          px={20}
        >
          <SimpleGrid columns={2} spacing={10} mb={4}>
            <div>
              <Heading as="h1" size="3xl" color="white" mb={4}>
                Las manos de la pachamama
              </Heading>
              <Text fontSize="md" color="gray.200">
                La Mano de la Pachamama está ubicada dentro del complejo El
                Vuelo del Cóndor en el sector de Runtún a 7 km del centro de la
                ciudad de Baños.
              </Text>
            </div>
          </SimpleGrid>
          <JumboForm />
        </Box>
      </Box>
    </Container>
  );
};

export default Home;
